name: CI

on:
  push:
    branches: [ main, develop, feature/**, hotfix/** ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and test (Maven verify)
        run: mvn -B -ntp verify

      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/*.xml'

      - name: Upload packaged jar
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: '**/target/*.jar'

